import type { Metadata } from 'next'
import './globals.css'
import { Header } from '@/components/base/Header'
import { Footer } from '@/components/base/Footer'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Header />
          <div className="min-h-screen py-0 px-2 flex flex-col justify-center items-center">
            {children}
          </div>
        <Footer />
      </body>
    </html>
  )
}
